// Generated by scripts/genFormConstraints.ts. Do not edit.
// Regenerate with `bun run gen:constraints` after changing an endpoint payload.
// These attributes are the pre-hydration layer: the browser enforces them before
// any script runs. After hydration the form decodes against the payload schema.

export const formConstraints = {
	'posts.create': {
		body: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		privacy: {
			required: true,
		},
	},
	'users.register': {
		username: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		password: {
			required: true,
			minLength: 8,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		email: {
			type: 'email',
			minLength: 6,
			maxLength: 998,
		},
	},
	'users.login': {
		id: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		password: {
			required: true,
			minLength: 1,
		},
	},
	'users.confirmDeletion': {
		token: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
	},
	'users.forgotPassword': {
		email: {
			required: true,
			type: 'email',
			minLength: 6,
			maxLength: 998,
		},
	},
	'users.resetPassword': {
		userId: {
			required: true,
			pattern:
				'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
		},
		token: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		password: {
			required: true,
			minLength: 8,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
	},
	'users.changePassword': {
		oldPassword: {
			required: true,
			minLength: 1,
		},
		newPassword: {
			required: true,
			minLength: 8,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
	},
	'users.updateProfile': {
		username: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		name: {
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		avatar_url: {
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		bio: {
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
	},
	'users.oauthLink': {
		userId: {},
		username: {
			required: true,
		},
		serviceData: {
			required: true,
		},
		profile: {
			required: true,
		},
		tokens: {
			required: true,
		},
	},
	'email.addEmail': {
		email: {
			required: true,
			type: 'email',
			minLength: 6,
			maxLength: 998,
		},
	},
	'email.verifyEmail': {
		token: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
	},
	'organizations.create': {
		slug: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		name: {
			required: true,
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
	},
	'organizations.update': {
		slug: {
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		name: {
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
	},
	'organizations.invite': {
		username: {
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
		email: {
			type: 'email',
			minLength: 6,
			maxLength: 998,
		},
	},
	'organizations.acceptInvitation': {
		code: {
			minLength: 1,
			pattern: '^\\S[\\s\\S]*\\S$|^\\S$|^$',
		},
	},
	'organizations.transferOwnership': {
		userId: {
			required: true,
			pattern:
				'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
		},
	},
	'organizations.transferBillingContact': {
		userId: {
			required: true,
			pattern:
				'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
		},
	},
} as const
